version: "3"

services:
  chats-service:
    build:
      dockerfile: docker/Dockerfile.dev
      context: .
    command: go run ./server.go
    ports:
      - 8001:8001
    env_file:
      - .env.dev
    volumes:
      - ./chats-service:/src
    networks:
      - chack-check-network

networks:
  chack-check-network:
    name: chack-check-network
    external: true