apiVersion: apps/v1
kind: Deployment
metadata:
  name: diffaction-chats-service-deployment
  labels:
    app: diffaction-chats-service
    name: diffaction-chats-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diffaction-chats-service
  template:
    metadata:
      labels:
        app: diffaction-chats-service
    spec:
      containers:
        - name: diffaction-chats-service
          image: artemowkin/diffaction-chats-service:latest
          ports:
            - containerPort: 8000
              name: web
            - containerPort: 9090
              name: grc
          env:
            - name: APP_USERS_GRPC_HOST
              value: "diffaction-users-service"
            - name: APP_USERS_GRPC_PORT
              value: "9090"
            - name: APP_PORT
              value: "8000"
            - name: APP_DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: chats-service-credentials
                  key: database_dsn
            - name: APP_RABBIT_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: url
            - name: APP_RABBIT_PUBLISHER_EXCHANGE_NAME
              value: stage_chats_exchange
            - name: APP_RABBIT_USERS_EXCHANGE_NAME
              value: stage_users_exchange
            - name: APP_RABBIT_CONSUMER_QUEUE_NAME
              value: stage_chats_queue
            - name: APP_GRPC_HOST
              value: "0.0.0.0"
            - name: APP_GRPC_PORT
              value: "9090"
            - name: APP_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: users-service-credentials
                  key: secret_key
            - name: FILES_SIGNATURE_KEY
              valueFrom:
                secretKeyRef:
                  name: files-service-credentials
                  key: signature_key

            - name: APP_REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: chats-service-credentials
                  key: redis_url

            - name: APP_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: chats-service-credentials
                  key: sentry_dsn

            - name: APP_RABBIT_RECOGNITION_QUEUE_NAME
              value: stage_chats_messages_recognition_queue

            - name: APP_RABBIT_RECOGNITION_EXCHANGE_NAME
              value: stage_recognition_exchange
