apiVersion: apps/v1
kind: Deployment
metadata:
  name: chack-chats-service-deployment
  labels:
    app: chack-chats-service
    name: chack-chats-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chack-chats-service
  template:
    metadata:
      labels:
        app: chack-chats-service
    spec:
      containers:
        - name: chack-chats-service
          image: artemowkin/diffaction-chats-service:latest
          ports:
            - containerPort: 8000
              name: web
            - containerPort: 9090
              name: grc
          env:
            - name: APP_USERS_GRPC_HOST
              value: "chack-users-service"
            - name: APP_USERS_GRPC_PORT
              value: "9090"
            - name: APP_PORT
              value: "8000"
            - name: APP_DATABASE_HOST
              value: chats-postgres-service
            - name: APP_DATABASE_PORT
              value: "5432"
            - name: APP_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: chats-service-credentials
                  key: database_user
            - name: APP_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chats-service-credentials
                  key: database_password
            - name: APP_DATABASE_NAME
              value: chats_db
            - name: APP_RABBIT_HOST
              value: rabbitmq
            - name: APP_RABBIT_PORT
              value: "5672"
            - name: APP_RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: user
            - name: APP_RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
            - name: APP_RABBIT_PUBLISHER_EXCHANGE_NAME
              value: chats_exchange
            - name: APP_RABBIT_USERS_EXCHANGE_NAME
              value: users_exchange
            - name: APP_RABBIT_CONSUMER_QUEUE_NAME
              value: chats_queue
            - name: APP_GRPC_HOST
              value: "0.0.0.0"
            - name: APP_GRPC_PORT
              value: "9090"
            - name: APP_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: users-service-credentials
                  key: secret_key
            - name: FILES_SIGNATURE_KEY
              valueFrom:
                secretKeyRef:
                  name: files-service-credentials
                  key: signature_key

            - name: APP_REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: chats-service-credentials
                  key: redis_url

            - name: APP_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: chats-service-credentials
                  key: sentry_dsn
