apiVersion: apps/v1
kind: Deployment
metadata:
  name: chack-chats-service-deployment
  labels:
    app: chack-chats-service
    name: chack-chats-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chack-chats-service
  template:
    metadata:
      labels:
        app: chack-chats-service
    spec:
      containers:
        - name: chack-chats-service
          image: artemowkin/chack-chats-service:latest
          ports:
            - containerPort: 8000
              name: web
            - containerPort: 9090
              name: grc
          env:
            - name: USERS_GRPC_HOST
              value: "chack-users-service"
            - name: USERS_GRPC_PORT
              value: "9090"
            - name: PORT
              value: "8000"
            - name: APP_DATABASE_HOST
              value: chats-postgres-service
            - name: APP_DATABASE_PORT
              value: "5432"
            - name: APP_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: chats-service-credentials
                  key: database_user
            - name: APP_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chats-service-credentials
                  key: database_password
            - name: APP_DATABASE_NAME
              value: chats_db
            - name: APP_RABBIT_HOST
              value: rabbitmq
            - name: APP_RABBIT_PORT
              value: "5672"
            - name: APP_RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: user
            - name: APP_RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
            - name: APP_RABBIT_PUBLISHER_EXCHANGE_NAME
              value: chats_exchange
            - name: GRPC_SERVER_HOST
              value: "0.0.0.0"
            - nam: GRPC_SERVER_PORT
              value: 9090
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: users-service-credentials
                  key: secret_key
