package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"chats-service/internal/infrastructure/api/graph/model"
	"context"
	"fmt"
)

// CreateMessage is the resolver for the createMessage field.
func (r *mutationResolver) CreateMessage(ctx context.Context, request model.CreateMessageRequest) (model.MessageErrorResponse, error) {
	panic(fmt.Errorf("not implemented: CreateMessage - createMessage"))
}

// EditMessage is the resolver for the editMessage field.
func (r *mutationResolver) EditMessage(ctx context.Context, messageID int, request model.ChangeMessageRequest) (model.MessageErrorResponse, error) {
	panic(fmt.Errorf("not implemented: EditMessage - editMessage"))
}

// CreateChat is the resolver for the createChat field.
func (r *mutationResolver) CreateChat(ctx context.Context, request model.CreateChatRequest) (model.ChatErrorResponse, error) {
	panic(fmt.Errorf("not implemented: CreateChat - createChat"))
}

// ReadMessage is the resolver for the readMessage field.
func (r *mutationResolver) ReadMessage(ctx context.Context, messageID int) (model.MessageErrorResponse, error) {
	panic(fmt.Errorf("not implemented: ReadMessage - readMessage"))
}

// ReactMessage is the resolver for the reactMessage field.
func (r *mutationResolver) ReactMessage(ctx context.Context, messageID int, content string) (model.MessageErrorResponse, error) {
	panic(fmt.Errorf("not implemented: ReactMessage - reactMessage"))
}

// DeleteMessageReaction is the resolver for the deleteMessageReaction field.
func (r *mutationResolver) DeleteMessageReaction(ctx context.Context, messageID int) (model.MessageErrorResponse, error) {
	panic(fmt.Errorf("not implemented: DeleteMessageReaction - deleteMessageReaction"))
}

// DeleteMessage is the resolver for the deleteMessage field.
func (r *mutationResolver) DeleteMessage(ctx context.Context, messageID int) (model.BooleanResultErrorResponse, error) {
	panic(fmt.Errorf("not implemented: DeleteMessage - deleteMessage"))
}

// DeleteChat is the resolver for the deleteChat field.
func (r *mutationResolver) DeleteChat(ctx context.Context, chatID int) (model.BooleanResultErrorResponse, error) {
	panic(fmt.Errorf("not implemented: DeleteChat - deleteChat"))
}

// SendUserAction is the resolver for the sendUserAction field.
func (r *mutationResolver) SendUserAction(ctx context.Context, chatID int, actionType model.ActionTypes) (model.BooleanResultErrorResponse, error) {
	panic(fmt.Errorf("not implemented: SendUserAction - sendUserAction"))
}

// StopUserAction is the resolver for the stopUserAction field.
func (r *mutationResolver) StopUserAction(ctx context.Context, chatID int, actionType model.ActionTypes) (model.BooleanResultErrorResponse, error) {
	panic(fmt.Errorf("not implemented: StopUserAction - stopUserAction"))
}

// AddMembers is the resolver for the addMembers field.
func (r *mutationResolver) AddMembers(ctx context.Context, chatID int, members []int) (model.ChatErrorResponse, error) {
	panic(fmt.Errorf("not implemented: AddMembers - addMembers"))
}

// AddAdmins is the resolver for the addAdmins field.
func (r *mutationResolver) AddAdmins(ctx context.Context, chatID int, admins []int) (model.ChatErrorResponse, error) {
	panic(fmt.Errorf("not implemented: AddAdmins - addAdmins"))
}

// RemoveMembers is the resolver for the removeMembers field.
func (r *mutationResolver) RemoveMembers(ctx context.Context, chatID int, members []int) (model.ChatErrorResponse, error) {
	panic(fmt.Errorf("not implemented: RemoveMembers - removeMembers"))
}

// RemoveAdmins is the resolver for the removeAdmins field.
func (r *mutationResolver) RemoveAdmins(ctx context.Context, chatID int, admins []int) (model.ChatErrorResponse, error) {
	panic(fmt.Errorf("not implemented: RemoveAdmins - removeAdmins"))
}

// QuitChat is the resolver for the quitChat field.
func (r *mutationResolver) QuitChat(ctx context.Context, chatID int) (model.ChatErrorResponse, error) {
	panic(fmt.Errorf("not implemented: QuitChat - quitChat"))
}

// ChangeGroupChat is the resolver for the changeGroupChat field.
func (r *mutationResolver) ChangeGroupChat(ctx context.Context, chatID int, chatData model.ChangeGroupChatData) (model.ChatErrorResponse, error) {
	panic(fmt.Errorf("not implemented: ChangeGroupChat - changeGroupChat"))
}

// UpdateGroupChatAvatar is the resolver for the updateGroupChatAvatar field.
func (r *mutationResolver) UpdateGroupChatAvatar(ctx context.Context, chatID int, avatar model.UploadingFile) (model.ChatErrorResponse, error) {
	panic(fmt.Errorf("not implemented: UpdateGroupChatAvatar - updateGroupChatAvatar"))
}

// GetChatMessages is the resolver for the getChatMessages field.
func (r *queryResolver) GetChatMessages(ctx context.Context, chatID int, offset *int, limit *int) (model.PaginatedMessagesErrorResponse, error) {
	panic(fmt.Errorf("not implemented: GetChatMessages - getChatMessages"))
}

// GetChatMessagesByCursor is the resolver for the getChatMessagesByCursor field.
func (r *queryResolver) GetChatMessagesByCursor(ctx context.Context, chatID int, messageID int, aroundOffset *int) (model.PaginatedMessagesErrorResponse, error) {
	panic(fmt.Errorf("not implemented: GetChatMessagesByCursor - getChatMessagesByCursor"))
}

// GetChats is the resolver for the getChats field.
func (r *queryResolver) GetChats(ctx context.Context, page *int, perPage *int) (model.PaginatedChatsErrorResponse, error) {
	panic(fmt.Errorf("not implemented: GetChats - getChats"))
}

// GetChat is the resolver for the getChat field.
func (r *queryResolver) GetChat(ctx context.Context, chatID int) (model.ChatErrorResponse, error) {
	panic(fmt.Errorf("not implemented: GetChat - getChat"))
}

// GetLastMessagesForChats is the resolver for the getLastMessagesForChats field.
func (r *queryResolver) GetLastMessagesForChats(ctx context.Context, chatIds []int) (model.MessagesArrayErrorResponse, error) {
	panic(fmt.Errorf("not implemented: GetLastMessagesForChats - getLastMessagesForChats"))
}

// SearchChats is the resolver for the searchChats field.
func (r *queryResolver) SearchChats(ctx context.Context, query string, page *int, perPage *int) (model.PaginatedChatsErrorResponse, error) {
	panic(fmt.Errorf("not implemented: SearchChats - searchChats"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
